# Generated by Django 3.1.6 on 2021-02-11 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0002_sale_payment_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
    ]
