# Generated by Django 3.1.6 on 2021-02-14 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0003_remove_sale_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prod_inventory_app.product'),
            preserve_default=False,
        ),
    ]
