# Generated by Django 3.1.6 on 2021-02-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0004_auto_20210224_2031'),
        ('prod_inventory_app', '0003_auto_20210224_2223'),
    ]

    operations = [
    ]
