# Generated by Django 3.1.6 on 2021-02-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0005_merge_20210226_0656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
