# Generated by Django 3.1.6 on 2021-03-04 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0007_chart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
