# Generated by Django 3.1.6 on 2021-03-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0009_remove'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remove',
        ),
    ]
