# Generated by Django 3.1.6 on 2021-03-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0011_remove'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remove',
            name='payment_received',
        ),
        migrations.RemoveField(
            model_name='remove',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='remove',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
