# Generated by Django 3.1.6 on 2021-03-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0012_auto_20210319_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remove',
            name='reason',
        ),
    ]
