# Generated by Django 3.1.6 on 2021-03-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0013_remove_remove_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remove',
        ),
    ]
