# Generated by Django 3.1.6 on 2021-03-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0014_delete_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='remove_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
