# Generated by Django 3.1.6 on 2021-03-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0017_auto_20210319_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='remove',
            name='payment_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='remove',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
