# Generated by Django 3.1.6 on 2021-03-19 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0018_auto_20210319_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remove',
            name='payment_received',
        ),
        migrations.RemoveField(
            model_name='remove',
            name='unit_price',
        ),
    ]
