# Generated by Django 3.1.6 on 2021-03-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0019_auto_20210319_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remove',
            name='customer',
        ),
        migrations.AddField(
            model_name='remove',
            name='vendor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
