# Generated by Django 3.1.6 on 2021-03-22 05:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0022_auto_20210322_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod_inventory_app.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
