# Generated by Django 3.1.6 on 2021-03-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0024_auto_20210322_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remove',
            name='payment_received',
        ),
        migrations.RemoveField(
            model_name='remove',
            name='unit_price',
        ),
    ]
