# Generated by Django 3.1.6 on 2021-03-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0026_auto_20210322_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remove',
        ),
    ]
