# Generated by Django 3.1.6 on 2021-03-22 18:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0027_delete_remove'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('customer', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod_inventory_app.product')),
            ],
        ),
    ]
