# Generated by Django 3.1.6 on 2021-04-02 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0034_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovedReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='removed',
            name='reason1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prod_inventory_app.removedreason'),
        ),
    ]
