# Generated by Django 3.1.6 on 2021-04-02 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0035_auto_20210402_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='removed',
            name='reason1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prod_inventory_app.removedreason', verbose_name='Reason'),
        ),
    ]
