# Generated by Django 3.1.6 on 2021-04-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_inventory_app', '0037_remove_removed_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='removedreason',
            name='reason',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
